---
title: "Premier League 2020/21"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: bootstrap
editor_options: 
  chunk_output_type: console
---

<!-- Custom JS to help with formatting non-standard content -->
<script src="custom-flexdashboard-components.js"></script> 




```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(gt)
library(lubridate)
library(glue)
library(janitor)
library(scales)
library(DT)
library(htmltools)
library(rvest)

todays_date <- as_date(Sys.Date())
```


```{r}
data_path <- "~/R/projects/football/outputs/predictions/"

files <- dir(data_path, pattern = "*.csv") 


predictions <- files %>%
  map(function(x) read_csv(file.path(data_path, x))) %>%  
  reduce(rbind)
```


```{r}

results_fixtures <- read_csv("~/R/projects/football/outputs/results_fixtures.csv") %>% 
  mutate(Date = as_date(Date, tz = "GMT"), Date = Date + 1)

final_predictions <- predictions %>%  
  group_by(team_home, team_away) %>% 
  slice_max(date_ran) %>% 
  ungroup() %>% 
  select(-season_start, -gameweek, -date)


final_results <- results_fixtures %>% 
  select(Gameweek, Date, Time, HomeTeam, AwayTeam, FTHG, FTAG, AvgH, AvgD, AvgA) %>% 
  mutate(result = case_when(FTHG > FTAG ~ "W",
                            FTHG < FTAG ~ "L",
                            TRUE ~ "D")) %>% 
  left_join(final_predictions, by = c("HomeTeam" = "team_home",
                                    "AwayTeam" = "team_away")) %>% 
  drop_na %>% 
  mutate(accurate = case_when(result == .pred_class ~ TRUE,
                              TRUE ~ FALSE)) %>% 
  clean_names() %>%
  mutate(selected_odds = case_when(pred_class == "W" ~ avg_h,
                                   pred_class == "D" ~ avg_d,
                                   pred_class == "L" ~ avg_a)) %>% 
  mutate(outlay = 1) %>% 
  mutate(return = case_when(accurate == "TRUE" ~ selected_odds,
                            TRUE ~ 0))

```



Overview
=====================================  

Row {data-height=20}
-----------------------------------------------------------------------

```{r}
url <- 'https://www.football-data.co.uk/englandm.php'

webpage <- read_html(url)

date <- html_nodes(webpage,"i")[1] %>% 
  html_text() %>% 
  str_remove("\t") %>% 
  str_remove("Last updated: ")

text <- "Note: Results data from www.football-data.co.uk is available up to "

warning <- ". This may impact the data shown below"

text_to_include <- paste0(text, date, warning)
```

`r text_to_include`

Row
-----------------------------------------------------------------------

### Outlay 
```{r}
outlay <- sum(final_results$outlay)
return <- sum(final_results$return)
profit <- return - outlay
profit_for_colour <- profit
ROI <- (profit/outlay) * 100

outlay <- format(round(outlay, 2), nsmall = 2)
return <- format(round(return, 2), nsmall = 2)
profit <- format(round(profit, 2), nsmall = 2)
ROI <- format(round(ROI, 2), nsmall = 2)


outlay <- paste("€",outlay, sep = "")
return <- paste("€",return, sep = "")
profit <- paste("€",profit, sep = "")
ROI <- paste(ROI, "%", sep = "")

valueBox(outlay, 
         icon = "fas fa-minus",
         color = "red")
```


### Return 
```{r}
valueBox(return, 
         icon = "fas fa-plus",
         color = "green")


```


### Profit/Loss 
```{r}
profit_colour <- if (profit_for_colour >= 0) {
"green"
} else {
"red"
}
  
  

valueBox(profit, icon = "fas fa-money-bill-wave",
         color = profit_colour)
```

### ROI 
```{r}
valueBox(ROI, 
         icon = "fas fa-percent",
         color = profit_colour)

```



Row
-----------------------------------------------------------------------

### Predictions

```{r}
next_gameweek <- predictions %>%  
  group_by(team_home, team_away) %>% 
  slice_max(date_ran) %>% 
  filter(date >= todays_date) %>% 
  arrange(date) %>% 
  ungroup()

next_gameweek_table <- next_gameweek %>%
  select(-season_start, -gameweek, -date_ran) %>% 
  mutate(.pred_class = str_replace_all(.pred_class, c("L" = "Away",
                                                      "W" = "Home",
                                                      "D" = "Draw"))) %>% 
  rename("Match Date" = "date",
         "Away Team" = "team_away",
         "Home Team" = "team_home",
         "Home" = ".pred_W",
         "Draw" = ".pred_D",
         "Away" = ".pred_L",
         "Prediction" = ".pred_class")

gameweek <- as.integer(min(next_gameweek$gameweek))
date_ran <- as_date(min(next_gameweek$date_ran))

gt_table <- next_gameweek_table %>% 
  gt() %>% 
  tab_header(title = "Predictions", 
             subtitle = glue("Gameweek Starting: {gameweek}")) %>% 
  tab_source_note(source_note = glue("Date ran: {date_ran}")) %>% 
  fmt_percent(columns = vars(Home, Draw, Away)) %>%
  cols_align(columns = vars(Home, Draw, Away, Prediction), align = "center") %>%
  tab_spanner(label = "Weighting", columns = vars(Home, Draw, Away)) %>% 
  tab_options(source_notes.font.size = 10) %>% 
  data_color(columns = vars(Home, Draw, Away), 
             colors = scales::col_numeric(
               palette = c("red", "light green", "green", "dark green"),
               domain = c(0, 1))) 

div(gt_table, class='gt-no-scroll')
```

### Performance 

```{r}
final_results %>%  
  group_by(gameweek) %>%
  summarise(by_week = sum(return) - sum(outlay)) %>% 
  mutate(colour = case_when(by_week > 0 ~ "dark green",
                            TRUE ~ "red")) %>% 
  mutate(running = cumsum(by_week)) %>% 
  ggplot() +
  geom_point(aes(gameweek, running, colour = colour, size = 5), show.legend = FALSE) +
  geom_hline(yintercept = 0, colour = "grey") +
  scale_color_manual(values = c("dark green", "red")) +
  theme_light() +
  scale_y_continuous(labels = dollar_format(prefix = "€")) +
  labs(title = "Cumulative Profit/Loss",
       x = "Gameweek",
       y = "Profit/Loss (€)") +
  geom_line(aes(gameweek, running))
```


Row
-----------------------------------------------------------------------

### Returns

```{r}
accuracy <- final_results %>%  
  group_by(gameweek) %>%
  summarise(by_week = sum(return) - sum(outlay)) %>% 
  mutate(colour = case_when(by_week > 0 ~ "dark green",
                            TRUE ~ "red")) 

  ggplot(accuracy) +
  geom_col(aes(gameweek, by_week, fill = colour), show.legend = FALSE) +
  geom_hline(yintercept = 0, colour = "grey") +
  geom_hline(yintercept = mean(accuracy$by_week), colour = "black", linetype = 3, size = 1) +
  scale_fill_manual(values = c("dark green", "red")) +
  theme_light() +
  scale_y_continuous(labels = dollar_format(prefix = "€")) +
  labs(title = "Model Return by Gameweek",
       caption = "Dotted line indicates average return (by gameweek)",
       x = "Gameweek",
       y = "Return (€)")
```


### Success Rate

```{r}
accuracy_percent <- final_results %>%  
  mutate(success = case_when(accurate == TRUE ~ 1,
                             TRUE ~ 0),
         games = 1) %>%
  group_by(gameweek) %>% 
  summarise(accuracy = sum(success)/sum(games)) 



  ggplot(accuracy_percent) +
  geom_col(aes(gameweek, accuracy, fill = accuracy), show.legend = FALSE) +
  geom_hline(yintercept = 0, colour = "grey") +
  geom_hline(yintercept = mean(accuracy_percent$accuracy), colour = "black", linetype = 3, size = 1) +
  theme_light() +
  scale_y_continuous(labels = percent_format()) +
  labs(title = "Model Accuracy by Gameweek",
       caption = "Dotted line indicates average accuracy (by gameweek)",
       x = "Gameweek",
       y = "Accuracy (%)") +
  scale_fill_gradientn(colours = c("red", "orange", "light green", "dark green"), limits=c(0,1))
```






Raw Data
=====================================  


Row
-----------------------------------------------------------------------

### Results 

```{r}

datatable(final_results)

```




